### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path

### ISSUE THREAD

**Issue by 0x0foriv** [Strezzed/MavenMCP#24]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:2995)
	at net.minecraft.client.main.Main.main(Main.java:39)
	at Start.main(Start.java:11)

Process finished with exit code 1

Can someone help

**Comment by AnotherZane** [comment]
Make sure the path referencing to lwjgl jars is correct

**Comment by Pottinqq** [comment]
mine is correct but i get the same error
